### ISSUE TITLE
German downloads

### ISSUE THREAD

**Issue by Wunderharke** [leoncvlt/blinkist-scraper#1]
Is there any way to download German books and audios as well?
Could you add another flag to choose the language maybe?

I also ran into JSONDecodeErrors at some point in the program. I don't know when and why this happens exactly.

```
[.] Scraping book at https://www.blinkist.com/en/books/disrupted-en

Traceback (most recent call last):
  File ".\main.py", line 62, in <module>
    audio_files = scraper.scrape_book_audio(driver, book_json)
  File "[...]\scraper.py", line 223, in scrape_book_audio
    audio_url = audio_request.json()['url']
  File "[...]\Anaconda3\lib\site-packages\requests\models.py", line 889, in json
    self.content.decode(encoding), **kwargs
  File "[...]\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "[...]\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "[...]\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

PS: you should add Chrome browser to dependencies, as chomedriver needs Chrome browser to be installed.

**Comment by leoncvlt** [comment]
thanks for the feedback! b2c062e2d1c9e642b186c1a35533510a8bb7f018 Adds support for German langue with the `--language` argument, alongside with the `--match-language` option in case you want to download only books in german 🍻

As for the decoding error, I could not replicate that, but the latest commit 43aa262 should at least make it fail gracefully and not stop the scraping process. I'll close this but if you manage to replicate the error in a consistent way please give me a shout on #2

**Comment by Wunderharke** [comment]
Hi @leoncvlt,

thanks for the fast response and that easy to use language option!

The error above might just be a caching error, I canceled and restated scraping a few times.
I'll use a new repo clone this time and will report back here if I run into this again.
