### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 0xCuter** [leoncvlt/blinkist-scraper#13]
I get this syntax error while running main.py

`File "main.py", line 59
    print(f"[#] Processed {processed_books} books in {formatted_time}")
                                                                     ^
SyntaxError: invalid syntax`

If I try commenting that line I get other syntax errors in other files... I guess there is something wrong with my configuration

**Comment by leoncvlt** [comment]
Which Python version are you using? I think fstrings are supported from Python 3.6 onwards

**Comment by 0xCuter** [comment]
I tried updating and now I get this other error:
`File "main.py", line 3, in <module>
    import scraper
  File "/Users/.../Downloads/blinkist-scraper/scraper.py", line 3, in <module>
    from seleniumwire import webdriver
ModuleNotFoundError: No module named 'seleniumwire'`
Previously I installed all the requirements without errors...

**Comment by 0xCuter** [comment]
I resolved that, but now I get this other error when I try to run it

`selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist`

**Comment by 0xCuter** [comment]
I resolved adding this line in the scraper 
`chrome_options.add_argument('--no-sandbox')`

But now when chrome opens up I get this when loading the login page:
`Error response
Error code: 502

Message: Bad Gateway.

Error code explanation: 502 - Invalid responses from another server/proxy.`

**Comment by 0xCuter** [comment]
Ok, I resolved uncommenting the line You already put in the scraper for this error...
It looks like it's working fine
Thank You
