### ISSUE TITLE
Add a parameter to ignore SSL errors

### ISSUE THREAD

**Issue by auino** [leoncvlt/blinkist-scraper#19]
Referring to [502 errors](https://github.com/leoncvlt/blinkist-scraper/blob/master/blinkistscraper/scraper.py#L65), I'd suggest to add the possibility to ignore SSL errors by providing an optional command line parameter.

**Comment by johndoe-dev00** [comment]
Hi @auino,
at what point did you see the SSL error?
Could you post a screenshot?

**Comment by auino** [comment]
Sorry but I don’t remember anymore. Anyway, I managed to make it working as expected.
