### ISSUE TITLE
cannot execute main.py

### ISSUE THREAD

**Issue by sasagr** [leoncvlt/blinkist-scraper#23]
Hi. Really interested to use this script but I have serious difficulties to follow instructions as per README file.
Basic usage calls for python main.py without underscores.... but there is no such file.
Only similar file is __main__.py with underscores before and after main word in blinkistscraper folder but I guess it is not the right one.
Salvatores-MacBook-Pro:blinkistscraper salva$ python __main__.py user pass https://www.blinkist.com/en/nc/reader/the-box-en
  File "__main__.py", line 7
    log = logger.get(f"blinkistscraper")
                                      ^
SyntaxError: invalid syntax
Salvatores-MacBook-Pro:blinkistscraper salva$

Can you pls give more clear instruction on how to execute first command?
Thanks

**Comment by cryptoluks** [comment]
Try to execute it a directory above.

`python blinkistscraper/main.py user pass url`

**Comment by sasagr** [comment]
after upgrading to python3.8 and installing some missing modules I can run
python3.8 blinkistscraper/main.py user pass url --create-epub

But now I get this "Cannot contact reCAPTCHA. Check your connection and try again."
I see the connection is not sucure though I installed certs for python3.8
Any suggestion?

**Comment by sasagr** [comment]
fixed adding 127.0.0.1 as proxy

**Comment by Arminius4** [comment]
> Try to execute it a directory above.
> 
> `python blinkistscraper/main.py user pass url`

You also do not even need to give the python file to execute, because \_\_main__.py will be executed by default:

`python3 blinkistscraper user pass url`

**Comment by sasagr** [comment]
Ok, will do that.   
  
  
  

  
  

  
  
>
