### ISSUE TITLE
how to skip audio file?

### ISSUE THREAD

**Issue by sasagr** [leoncvlt/blinkist-scraper#24]
is there a command/argument I can give to skip the audio scraping, if I m interested in the ebook only?

**Comment by Arminius4** [comment]
Unfortunately, there is no command line option available yet for this use case. 
For now, if you can not implement this feature yourself, you'll have to resort to downloading the full books and deleting the audio later (you can also do this programmatically).

**Comment by Arminius4** [comment]
I just had a look in the __main.py__. There is the audio argument which you can set to `False` and it'll skip the audio download.

```
parser.add_argument(
        "--audio",
        action="store_true",
        default=True,
        help="Download the audio blinks for each book",
    )
```

**Comment by sasagr** [comment]
shall I make the change in the__main.py_file or I can add it as argument in the scraper command. I tried python3 blinkistscraper/__main__.py user pass --audio false --book url but it gives me error

**Comment by Arminius4** [comment]
Yes, change the code in the file

**Comment by sasagr** [comment]
ok. thanks

**Comment by leoncvlt** [comment]
It does make sense for the `--audio` argument to be `False` by deafult since with it being of `store_true` type, there's no way to turn it off via command line. I fixed this in e2956f992d7919e599163b8b0a95ab641cdbe89a 😃

**Comment by sasagr** [comment]
so if I m understanding it right, with the change of https://github.com/leoncvlt/blinkist-scraper/commit/e2956f992d7919e599163b8b0a95ab641cdbe89a with the simple scraping command we don't get audio scraping but only book. What shall I do if I want the audio as well? can I ask for it in the command line?

**Comment by leoncvlt** [comment]
Yup, you just add `--audio` to your command as specified in the readme.
