### ISSUE TITLE
Improve mac / linux compatibility

### ISSUE THREAD

**Issue by leoncvlt** [leoncvlt/blinkist-scraper#3]
Right now the script is hardcoded to use `chromedriver.exe` which obviously only works on windows. Should make the chromedriver path into a proper argument so people can use the windows or linux executable as well.

**Comment by nerrons** [comment]
macOS #7

**Comment by leoncvlt** [comment]
b044e46d728b402216e5ff211ca7c4396e4bb2d2 should make this work on both mac & linux!
