### ISSUE TITLE
Thank you first :)

### ISSUE THREAD

**Issue by kuanstu** [leoncvlt/blinkist-scraper#5]
Thank you first :)

i thought the book Homo Deus (https://www.blinkist.com/en/nc/reader/homo-deus-en) was in my dump & books folder, but i couldn't find it. 
It occurs to other 2 books by Yuval Noah Harari: Sapiens, 21 Lessons for the 21st Century. 

Would it be possible to be solved? ... Thank you so so much >_<

Homo Deus (https://www.blinkist.com/en/nc/reader/homo-deus-en) 
Sapiens (https://www.blinkist.com/en/nc/reader/sapiens-en)
21 Lessons for the 21st Century (https://www.blinkist.com/en/nc/reader/21-lessons-for-the-21st-century-en)

**Comment by leoncvlt** [comment]
Hey, I've just added support for single book scraping in 6d6fe3fe7c985d25782ef2230528b9e732502491. I have tried scraping those books singularly (e.g. `python main.py email password --book https://www.blinkist.com/en/nc/reader/21-lessons-for-the-21st-century-en`) and they seem to come out fine. Will you give it a shot as well and tell me if it's the same for you? Still can't explain why they would get skipped on a global pass.

Note that with scraping a single book they get output in the `Uncategorized` folder by default, so if you want to put the in a specific category use the `--category` flag as well 😉

**Comment by kuanstu** [comment]
Hey, leoncvlt !! 

Thanks your update.  ^ω^
It works and the outlet looks really nice as well. 
The new function(--book) is so useful to scrap and to sort out the books i like. (^o^)bb

However, when i ran another commend, it accidentally returned an error as following:
> C:\Users\USER\Desktop\blinkist-scraper-master>**python main.py  my_email my_password**
> [.] Initialising chromedriver...
> 
> DevTools listening on ws://127.0.0.1:10767/devtools/browser/308dec6e-4566-494d-9432-9beffc53b126
> [.] Getting all books for category Entrepreneurship...
> [.] Found 184 books
> Traceback (most recent call last):
>   File "main.py", line 80, in <module>
>     dump_exists = scrape_book(driver, processed_books, args.book, category=category, match_language=match_language)
>   File "main.py", line 39, in scrape_book
>     book_json, dump_exists = scraper.scrape_book(driver, book_url, category=category, match_language=match_language)
>   File "C:\Users\USER\Desktop\blinkist-scraper-master\scraper.py", line 134, in scrape_book
>     if (os.path.exists(get_book_dump_filename(book_url)) and not force):
>   File "C:\Users\USER\Desktop\blinkist-scraper-master\utils.py", line 12, in get_book_dump_filename
>     if ("blinkist.com" in book_json_or_url):
> TypeError: argument of type 'bool' is not iterable

Thank you, i really appreciate your help. ヾ(◍•ᴗ•◍)ﾉ

**Comment by leoncvlt** [comment]
Ah, sorry about this. Last commit ba44c7b94ed0f3f3371d120a68bd758682bead49 should make it work again 😉

**Comment by kuanstu** [comment]
So nice!! It performs well now. ヾ(◍•ᴗ•◍)ﾉ
