### ISSUE TITLE
infinite captcha: bug or scraper not working any more?

### ISSUE THREAD

**Issue by denupr** [leoncvlt/blinkist-scraper#59]
Hi all,

I have just tried the blinkist scraper with my free account. It does not work any more. It just pops up the captcha window. I insert them many times, then the captcha windows crashes and I get the following messages:

INFO Please solve captcha to proceed!
ERROR Error. Captcha needs to be solved within 1 minute
ERROR Unable to login into Blinkist
INFO Processed 0 books in 00:01:10

Any hints?

**Comment by thtsc** [comment]
I can confirm that I'm experiencing the exact same problem.

**Comment by hxh103** [comment]
hi @denupr, check issue #46, I think you're having the same problem and the solution(s) posted there should solve it. 
cheers

**Comment by leoncvlt** [comment]
Let's chat in #46
